#!/bin/sh

# Xmodmap
[ -f $HOME/.Xmodmap ] && xmodmap $HOME/.Xmodmap

# Rxvt-unicode
urxvtd -q -o -f

eval `dbus-launch --sh-syntax --exit-with-session`

# Fcitx IME
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
killall fcitx
fcitx &

# PC Speaker
xset -b
