#!/bin/sh

# Rxvt-unicode
if which urxvtd &>/dev/null; then
	urxvtd -q -o -f
fi

eval `dbus-launch --sh-syntax --exit-with-session`

# Fcitx IME
if which fcitx &>/dev/null; then
	export XMODIFIERS="@im=fcitx"
	export GTK_IM_MODULE=fcitx
	export QT_IM_MODULE=fcitx
	killall fcitx
	fcitx &
fi

export ALSA_CARD=G4ME1

# PC Speaker
xset -b
