#!/bin/sh

# Rxvt-unicode
if which urxvtd &>/dev/null; then
	urxvtd -q -o -f
fi

# IBus IME
if which ibus-daemon &>/dev/null; then
	export XMODIFIERS="@im=ibus"
	export GTK_IM_MODULE=ibus
	export QT_IM_MODULE=ibus
	ibus-daemon -d -x
fi
